# This rule is not used by the project gostration itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over workflow.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gostration
    app.kubernetes.io/managed-by: kustomize
  name: dag-admin-role
rules:
- apiGroups:
  - workflow.my.domain
  resources:
  - dags
  verbs:
  - '*'
- apiGroups:
  - workflow.my.domain
  resources:
  - dags/status
  verbs:
  - get
