# This rule is not used by the project gostration itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the workflow.my.domain.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gostration
    app.kubernetes.io/managed-by: kustomize
  name: dag-editor-role
rules:
- apiGroups:
  - workflow.my.domain
  resources:
  - dags
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workflow.my.domain
  resources:
  - dags/status
  verbs:
  - get
