apiVersion: workflow.my.domain/v1
kind: Dag
metadata:
  labels:
    app.kubernetes.io/name: gostration
    app.kubernetes.io/managed-by: kustomize
  name: dag-sample
spec:
  # TODO(user): Add fields here
