apiVersion: workflow.nautikus.io/v1
kind: Dag
metadata:
  labels:
    app.kubernetes.io/name: nautikus
    app.kubernetes.io/managed-by: kustomize
  name: dag-sample
spec:
  # TODO(user): Add fields here
